### ISSUE TITLE
[Bug] jQuery 1.7.2 with easing plugin

### ISSUE THREAD

**Issue by imken** [fredleblanc/roundabout#37] opened 2012-05-30 11:22 UTC
when using jQuery 1.7.2  with easing plugin 1.3

and the roundabout  animation will be cary mess up....

please fix it,  thanks a lot a lot a lot.......

**Comment by fredleblanc** [comment] 2012-05-31 19:23
This is a duplicate of [#29](https://github.com/fredhq/roundabout/issues/29). Closing this issue, although the other is still open.

**Closed as completed by fredleblanc** 2012-05-31 19:23 UTC
