### ISSUE TITLE
Handling only two items

### ISSUE THREAD

**Issue by johnsardine** [fredleblanc/roundabout#43] opened 2012-06-19 06:44 UTC
If i have only two items in the script, one stays in front of the other and the one on the back cant be seen or touched, it seems that only one exists, how can i improve this? Thank you

**Comment by fredleblanc** [comment] 2012-06-25 14:34
Roundabout will evenly disperse moving items around the shape that you set, so for the default shape (which you could think of a circle), it will put one at 0° and one at 180°. As you can tell, this means that you can't see the second one because it's hiding behind the one at 0°. This is expected behavior.

To only show two things, try adding a third thing that is empty. This should move the position of the items to be 0°, 120° and 240° (splitting 360° by three), hopefully you'll be able to see both of the things that aren't empty.

The other solution would be to create a custom shape, but that's a lot more work and math.

**Closed as completed by fredleblanc** 2012-06-25 14:34 UTC
